[package]
name = "wasm-sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "2.3.0"
anyhow = "1.0.65"
linkme = "*"
wast = "47.0.1"
